name: Build APK

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer

      - name: Install Cython
        run: |
          pip install Cython

      - name: Install moviepy
        run: |
          pip install moviepy

      - name: Install pytube
        run: |
          pip install pytube

      - name: Install build-essential
        run: |
          sudo apt-get update
          sudo apt-get install build-essential

      - name: Install libstdc++6
        run: |
          sudo apt-get install libstdc++6

      - name: Install AIDL
        run: |
          sudo apt-get install aidl

      - name: Build APK
        run: |
          buildozer -v android debug
